FROM openjdk:8-jdk-alpine
EXPOSE 8081
ADD SwipingSammiesBackend/build/libs/SwipingSammiesBackend-0.0.1-SNAPSHOT.jar SwipingSammiesBackend-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "SwipingSammiesBackend-0.0.1-SNAPSHOT.jar"]

